name: Build listing

on:
  push:
    branches: [ "master" ]
    paths:
    - .github/workflows/build-listing.yml
    - Synapse.Networking/**
    - Synapse.Listing/**
    - Synapse.sln

jobs:
  build:
    name: Build listing
    uses: Aeroluna/workflows/.github/workflows/docker-build-image.yml@main
    with:
      registry: ghcr.io
      image-name: synapse-listing
      dockerfile: Synapse.Listing/Dockerfile
    secrets: inherit