name: Build server

on:
  push:
    branches: [ "master" ]
    paths:
    - .github/workflows/build-server.yml
    - Synapse.Networking/**
    - Synapse.Server/**
    - Synapse.sln

jobs:
  build:
    name: Build server
    uses: Aeroluna/workflows/.github/workflows/docker-build-image.yml@main
    with:
      registry: ghcr.io
      image-name: synapse-server
      dockerfile: Synapse.Server/Dockerfile
    secrets: inherit