name: Build mod

on:
  push:
    branches: [ "master" ]
    paths:
    - .github/workflows/build-mod.yml
    - Synapse.Networking/**
    - Synapse/**
    - Synapse.sln

jobs:
  build:
    name: Build mod
    strategy:
      matrix:
        game-version: [ 1.29.1, 1.34.2, 1.37.1, 1.39.1, 1.40.0 ]
    uses: Aeroluna/workflows/.github/workflows/bs-build-version-release.yml@main
    with:
      project-path: Synapse/Synapse.csproj
      game-version: ${{ matrix.game-version }}
    secrets: inherit

  create_release:
    name: Create Release
    needs: build
    permissions:
      contents: write
    uses: Aeroluna/workflows/.github/workflows/bs-create-release-from-project.yml@main
    with:
      project-path: Synapse/Synapse.csproj
    secrets: inherit
